// BLADED OR SHARP POLEARMS
//~=========================~


// THE HALBERD!
// So Knightly!
class doso_halberd:doso_weap{
	default{
		doso_weap.world "doso_halberd_w";
	}
	states{
	spawn:
		LSRD S -1;
		stop;
	}
}

class doso_halberd_w:doso_weap_w{
	default{
		doso_weap_w.mass 2.06,168;
		doso_weap_w.blade 42,10;
		doso_weap_w.bladestart 29;
		doso_weap_w.size 60,3;
		doso_weap_w.maxextend 18;
		doso_weap_w.sharpness 0.85,0.65;
		doso_weap_w.sprite 'TNT1';
	}
}